yekindar = {    "Nickname": "YekidnaR",     "Rating": 1.04, "Kills": 1040, "Deaths": 1000, "Trophys": 0, "MVP": False, "Team": None}
electronic = {  "Nickname": "electroNic",   "Rating": 0.98, "Kills": 980,  "Deaths": 1000, "Trophys": 0, "MVP": False, "Team": None}
rain = {        "Nickname": "rain",         "Rating": 1.09, "Kills": 1090, "Deaths": 1000, "Trophys": 0, "MVP": False, "Team": None}
apex = {        "Nickname": "apEX",         "Rating": 0.95, "Kills": 950,  "Deaths": 1000, "Trophys": 0, "MVP": False, "Team": None}
n910 = {         "Nickname": "910",         "Rating": 1.05, "Kills": 1050, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
niko = {        "Nickname": "Niko",         "Rating": 1.20, "Kills": 1200, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
frozen = {      "Nickname": "frozen",       "Rating": 1.18, "Kills": 1180, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
b1t = {         "Nickname": "b1t",          "Rating": 1.17, "Kills": 1170, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
elige = {       "Nickname": "EliGE",        "Rating": 1.21, "Kills": 1210, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
donk = {        "Nickname": "donk",         "Rating": 1.38, "Kills": 1380, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
ropz = {        "Nickname": "ropz",         "Rating": 1.11, "Kills": 1110, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
xantares = {    "Nickname": "XANTARES",     "Rating": 1.19, "Kills": 1190, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
perfecto = {    "Nickname": "Perfecto",     "Rating": 0.92, "Kills": 920,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
interz = {      "Nickname": "Interz",       "Rating": 1.01, "Kills": 1010, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
nitr0 = {       "Nickname": "nitr0",        "Rating": 1.10, "Kills": 1100, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
malbsMd = {     "Nickname": "malbsMd",      "Rating": 1.05, "Kills": 1050, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
magisk = {      "Nickname": "Magisk",       "Rating": 0.92, "Kills": 920,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
s1mple = {      "Nickname": "S1mple",       "Rating": 1.33, "Kills": 1330, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
zywoo = {       "Nickname": "ZywOo",        "Rating": 1.23, "Kills": 1230, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
sh1ro = {       "Nickname": "Sh1ro",        "Rating": 1.23, "Kills": 1230, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
m0nesy = {      "Nickname": "m0NESY",       "Rating": 1.16, "Kills": 1160, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
device = {      "Nickname": "device",       "Rating": 1.13, "Kills": 1130, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
woxic = {       "Nickname": "woxic",        "Rating": 1.14, "Kills": 1140, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
karrigan = {    "Nickname": "karrigan",     "Rating": 0.79, "Kills": 790,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
FalleN = {      "Nickname": "FalleN",       "Rating": 0.96, "Kills": 960,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
gla1ve = {      "Nickname": "gla1ve",       "Rating": 0.90, "Kills": 900,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
snappi = {      "Nickname": "Snappy",       "Rating": 0.96, "Kills": 960,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
boombl4 = {     "Nickname": "Boombl4",      "Rating": 0.96, "Kills": 960,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
blamef = {      "Nickname": "blameF",       "Rating": 1.15, "Kills": 1150, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
nafany = {      "Nickname": "nafany",       "Rating": 1.11, "Kills": 1110, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
zont1x = {      "Nickname": "zont1x",       "Rating": 1.04, "Kills": 1040, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
jl = {          "Nickname": "jL",           "Rating": 1.00, "Kills": 1000, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
im = {          "Nickname": "iM",           "Rating": 1.06, "Kills": 1060, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
aleksib = {     "Nickname": "Aleksib",      "Rating": 0.94, "Kills": 940,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
w0nderful = {   "Nickname": "w0nderful",    "Rating": 1.16, "Kills": 1160, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
jcobbb = {      "Nickname": "jcobbb",       "Rating": 1.12, "Kills": 1120, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
hewyxy = {      "Nickname": "Hewyxy",       "Rating": 1.13, "Kills": 1130, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
hunter ={       "Nickname": "huNter",       "Rating": 1.04, "Kills": 1040, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
ax1le = {       "Nickname": "Ax1le",        "Rating": 1.08, "Kills": 1080, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
k1LL3R00S1X = { "Nickname": "K1LL3R00S1X",  "Rating": 0.92, "Kills": 920,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
npl = {         "Nickname": "npl",          "Rating": 1.11, "Kills": 1110, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
headtr1ck = {   "Nickname": "headtr1ck",    "Rating": 0.96, "Kills": 960,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
kyousuke = {    "Nickname": "kyousuke",     "Rating": 1.21, "Kills": 1210, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
deko = {        "Nickname": "deko",         "Rating": 1.22, "Kills": 1220, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
flameZ = {      "Nickname": "flameZ",       "Rating": 1.10, "Kills": 1100, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
nIGHT666LADE = {"Nickname": "NIGHT666LADE", "Rating": 1.12, "Kills": 1120, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
brollan = {     "Nickname": "Brollan",      "Rating": 0.98, "Kills": 980,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
torzsi = {      "Nickname": "torzsi",       "Rating": 1.12, "Kills": 1120, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
spinx = {       "Nickname": "Spinx",        "Rating": 1.04, "Kills": 1040, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
xeritoN = {     "Nickname": "xeritoN",      "Rating": 1.09, "Kills": 1090, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
mAJ3R = {       "Nickname": "MAJ3R",        "Rating": 0.82, "Kills": 820,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
wicadia = {     "Nickname": "Wicadia",      "Rating": 1.14, "Kills": 1140, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
heavyGod = {    "Nickname": "HeavyGod",     "Rating": 1.17, "Kills": 1170, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
bLitz = {       "Nickname": "bLitz",        "Rating": 1.06, "Kills": 1060, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
techno = {      "Nickname": "Techno",       "Rating": 1.09, "Kills": 1090, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
senzu = {       "Nickname": "Senzu",        "Rating": 1.14, "Kills": 1140, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
mzinho = {      "Nickname": "mzinho",       "Rating": 1.07, "Kills": 1070, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
teses = {       "Nickname": "TeSeS",        "Rating": 1.03, "Kills": 1030, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
degster = {     "Nickname": "degster",      "Rating": 1.03, "Kills": 1030, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
jabbi = {       "Nickname": "jabbi",        "Rating": 1.13, "Kills": 1130, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
HooXi = {       "Nickname": "HooXi",        "Rating": 0.91, "Kills": 910,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
twistzz = {     "Nickname": "Twistzz",      "Rating": 1.11, "Kills": 1110, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
siuhy = {       "Nickname": "siuhy",        "Rating": 0.86, "Kills": 860,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
dem0n = {       "Nickname": "dem0n",        "Rating": 1.22, "Kills": 1220, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
cmtry = {       "Nickname": "cmtry",        "Rating": 0.99, "Kills": 990,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
jame = {        "Nickname": "Jame",         "Rating": 1.14, "Kills": 1140, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
hobbit = {      "Nickname": "Hobbit",       "Rating": 1.08, "Kills": 1080, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
Oneeer = {      "Nickname": "1eer",         "Rating": 0.94, "Kills": 940,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
riskyb0b = {    "Nickname": "riskyb0b",     "Rating": 1.00, "Kills": 1000, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
khaN = {        "Nickname": "khaN",         "Rating": 1.04, "Kills": 1040, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
zweih = {       "Nickname": "zweih",        "Rating": 0.97, "Kills": 970,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
wojx = {        "Nickname": "wojx",         "Rating": 1.12, "Kills": 1210, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
tn1r = {        "Nickname": "tN1R",         "Rating": 1.15, "Kills": 1150, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
sdy = {         "Nickname": "sdy",          "Rating": 1.08, "Kills": 1080, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
makazze = {     "Nickname": "makazze",      "Rating": 1.13, "Kills": 1130, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
molodoy = {     "Nickname": "molodoy",      "Rating": 1.16, "Kills": 1160, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
sh1n = {        "Nickname": "sh1n",         "Rating": 1.28, "Kills": 1280, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
tO0RO = {       "Nickname": "tO0RO",        "Rating": 1.10, "Kills": 1100, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
fl1t = {        "Nickname": "FL1T",         "Rating": 1.07, "Kills": 1070, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
icy = {         "Nickname": "ICY",          "Rating": 0.96, "Kills": 960,  "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
fame = {        "Nickname": "fame",         "Rating": 1.04, "Kills": 1040, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}
fL4MUS = {      "Nickname": "FL4MUS",       "Rating": 1.06, "Kills": 1060, "Deaths": 1000, "Trophys": 0, "MVP": False , "Team": None}




players = [tO0RO, sh1n, molodoy,makazze, tn1r,sdy,wojx ,zweih,khaN,riskyb0b,Oneeer,jame,hobbit,cmtry, dem0n, siuhy,twistzz, HooXi, jabbi, degster, teses, mzinho, senzu, techno, bLitz, heavyGod, wicadia, mAJ3R, xeritoN, spinx, torzsi, brollan, yekindar, electronic, rain, apex, n910, niko, frozen, b1t, elige, donk, ropz, xantares, perfecto, interz, nitr0, malbsMd, magisk, s1mple, zywoo, sh1ro, m0nesy, device, woxic, karrigan, FalleN, gla1ve, snappi, boombl4, blamef, nafany, zont1x, jl, im, aleksib, w0nderful,jcobbb ,hewyxy, hunter,ax1le, k1LL3R00S1X,npl,headtr1ck,kyousuke,deko,flameZ,nIGHT666LADE]
allPlayers = players

teamNames = ["Vitality", "Spirit", "MOUZ", "NAVI", "G2", "FaZe", "Falcons", "Liquid", "Virtus.pro", "Astralis", "Furia", "Aurora", "PaiN", "The MongolZ"]

teamP = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}, "is_user": True}
team1 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team2 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team3 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team4 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team5 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team6 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team7 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team8 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team9 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team10 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team11 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team12 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team13 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}


teamsList = [team1, team2, team3, team4, team5, team6, team7, team8, team9, team10, team11, team12, team13, teamP]