yekindar = {"Nickname": "YekidnaR", "Rating": 1.08, "Kills": 108, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
electronic = {"Nickname": "electroNic", "Rating": 0.96, "Kills": 96, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
rain = {"Nickname": "rain", "Rating": 1.07, "Kills": 107, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
apex = {"Nickname": "apEX", "Rating": 1.02, "Kills": 102, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
dupreeh = {"Nickname": "dupreeh", "Rating": 1.07, "Kills": 107, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
niko = {"Nickname": "Niko", "Rating": 1.10, "Kills": 110, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
frozen = {"Nickname": "frozen", "Rating": 1.13, "Kills": 113, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
b1t = {"Nickname": "b1t", "Rating": 1.03, "Kills": 103, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
elige = {"Nickname": "EliGE", "Rating": 1.10, "Kills": 110, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
donk = {"Nickname": "donk", "Rating": 1.45, "Kills": 145, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
ropz = {"Nickname": "ropz", "Rating": 1.19, "Kills": 119, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
xantares = {"Nickname": "XANTARES", "Rating": 1.18, "Kills": 118, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
perfecto = {"Nickname": "Perfecto", "Rating": 1.00, "Kills": 100, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
interz = {"Nickname": "Interz", "Rating": 0.99, "Kills": 99, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
nitr0 = {"Nickname": "nitr0", "Rating": 0.98, "Kills": 98, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
xyp9x = {"Nickname": "Xyp9x", "Rating": 1.01, "Kills": 101, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
magisk = {"Nickname": "Magisk", "Rating": 1.01, "Kills": 101, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
s1mple = {"Nickname": "S1mple", "Rating": 1.12, "Kills": 112, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
zywoo = {"Nickname": "ZywOo", "Rating": 1.33, "Kills": 133, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
sh1ro = {"Nickname": "Sh1ro", "Rating": 1.24, "Kills": 124, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
m0nesy = {"Nickname": "m0NESY", "Rating": 1.22, "Kills": 122, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
device = {"Nickname": "device", "Rating": 1.15, "Kills": 115, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
woxic = {"Nickname": "woxic", "Rating": 1.02, "Kills": 102, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
karrigan = {"Nickname": "karrigan", "Rating": 0.86, "Kills": 86, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
cadian = {"Nickname": "cadiaN", "Rating": 1.03, "Kills": 103, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
gla1ve = {"Nickname": "gla1ve", "Rating": 0.92, "Kills": 92, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
snappi = {"Nickname": "Snappy", "Rating": 0.95, "Kills": 95, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
boombl4 = {"Nickname": "Boombl4", "Rating": 0.95, "Kills": 95, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
blamef = {"Nickname": "blameF", "Rating": 1.24, "Kills": 124, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
f0rest = {"Nickname": "f0rest", "Rating": 1.10, "Kills": 110, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
zont1x = {"Nickname": "zont1x", "Rating": 1.07, "Kills": 107, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
jl = {"Nickname": "jL", "Rating": 1.07, "Kills": 107, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
im = {"Nickname": "iM", "Rating": 1.06, "Kills": 106, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
aleksib = {"Nickname": "Aleksib", "Rating": 0.93, "Kills": 93, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
w0nderful = {"Nickname": "w0nderful", "Rating": 1.09, "Kills": 109, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
snax = {"Nickname": "Snax", "Rating": 0.92, "Kills": 92, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
hewyxy = {"Nickname": "Hewyxy", "Rating": 1.29, "Kills": 129, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
hunter = {"Nickname": "huNter", "Rating": 1.06, "Kills": 106, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
ax1le = {"Nickname": "Ax1le", "Rating": 0.94, "Kills": 94, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
merl = {"Nickname": "Merl", "Rating": 0.91, "Kills": 91, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
npl = {"Nickname": "npl", "Rating": 1.14, "Kills": 114, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
headtr1ck = {"Nickname": "headtr1ck", "Rating": 1.05, "Kills": 105, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
kyousuke = {"Nickname": "kyousuke", "Rating": 1.38, "Kills": 138, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
deko = {"Nickname": "deko", "Rating": 1.22, "Kills": 122, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
flameZ = {"Nickname": "flameZ", "Rating": 1.08, "Kills": 108, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
nIGHT666LADE = {"Nickname": "NIGHT666LADE", "Rating": 0.90, "Kills": 90, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
brollan = {"Nickname": "Brollan", "Rating": 0.90, "Kills": 90, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
torzsi = {"Nickname": "torzsi", "Rating": 1.05, "Kills": 105, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
spinx = {"Nickname": "Spinx", "Rating": 1.10, "Kills": 110, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
xeritoN = {"Nickname": "xeritoN", "Rating": 1.14, "Kills": 114, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
mAJ3R = {"Nickname": "MAJ3R", "Rating": 0.87, "Kills": 87, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
wicadia = {"Nickname": "Wicadia", "Rating": 1.09, "Kills": 109, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
heavyGod = {"Nickname": "HeavyGod", "Rating": 1.14, "Kills": 114, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
bLitz = {"Nickname": "bLitz", "Rating": 1.05, "Kills": 105, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
techno = {"Nickname": "Techno", "Rating": 0.96, "Kills": 96, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
senzu = {"Nickname": "Senzu", "Rating": 1.18, "Kills": 118, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
mzinho = {"Nickname": "mzinho", "Rating": 1.00, "Kills": 100, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
teses = {"Nickname": "TeSeS", "Rating": 1.03, "Kills": 103, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
degster = {"Nickname": "degster", "Rating": 1.03, "Kills": 103, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
dosia = {"Nickname": "Dosia", "Rating": 0.98, "Kills": 98, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
zeus = {"Nickname": "Zeus", "Rating": 0.92, "Kills": 92, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
twistzz = {"Nickname": "Twistzz", "Rating": 1.03, "Kills": 103, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
siuhy = {"Nickname": "siuhy", "Rating": 0.88, "Kills": 88, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
dem0n = {"Nickname": "dem0n", "Rating": 1.19, "Kills": 119, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
cmtry = {"Nickname": "cmtry", "Rating": 1.01, "Kills": 101, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
jame = {"Nickname": "Jame", "Rating": 1.19, "Kills": 119, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
hobbit = {"Nickname": "Hobbit", "Rating": 1.09, "Kills": 109, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
Xant3r = {"Nickname": "Xant3r", "Rating": 1.04, "Kills": 104, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
Oneeer = {"Nickname": "1eer", "Rating": 0.92, "Kills": 92, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
riskyb0b = {"Nickname": "riskyb0b", "Rating": 0.93, "Kills": 93, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
khaN = {"Nickname": "khaN", "Rating": 1.06, "Kills": 106, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
zweih = {"Nickname": "zweih", "Rating": 1.11, "Kills": 111, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
wojx = {"Nickname": "wojx", "Rating": 1.23, "Kills": 123, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
tn1r = {"Nickname": "tN1R", "Rating": 1.21, "Kills": 121, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
sdy = {"Nickname": "sdy", "Rating": 1.16, "Kills": 116, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
makazze = {"Nickname": "makazze", "Rating": 1.24, "Kills": 124, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}
molodoy = {"Nickname": "molodoy", "Rating": 1.12, "Kills": 112, "Deaths": 100, "Trophys": 0, "MVPs": [], "Team": None}




players = [molodoy,makazze, tn1r,sdy,wojx ,zweih,khaN,riskyb0b,Oneeer,Xant3r,jame,hobbit,cmtry, dem0n, siuhy,twistzz, zeus, dosia, degster, teses, mzinho, senzu, techno, bLitz, heavyGod, wicadia, mAJ3R, xeritoN, spinx, torzsi, brollan, yekindar, electronic, rain, apex, dupreeh, niko, frozen, b1t, elige, donk, ropz, xantares, perfecto, interz, nitr0, xyp9x, magisk, s1mple, zywoo, sh1ro, m0nesy, device, woxic, karrigan, cadian, gla1ve, snappi, boombl4, blamef, f0rest, zont1x, jl, im, aleksib, w0nderful,snax,hewyxy,hunter,ax1le,merl,npl,headtr1ck,kyousuke,deko,flameZ,nIGHT666LADE]
allPlayers = players

teamNames = ["Vitality", "Spirit", "MOUZ", "NAVI", "G2", "FaZe", "Falcons", "Liquid", "Virtus.pro", "Astralis", "Furia", "Aurora", "PaiN", "The MongolZ"]

teamP = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}, "is_user": True}
team1 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team2 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team3 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team4 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team5 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team6 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team7 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team8 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team9 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team10 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team11 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team12 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}
team13 = {"Name": None, "Points": 0, "Earing": 0, "Players": [], "Wins": 0, "Losses": 0, "Trophys": {}}


teamsList = [team1, team2, team3, team4, team5, team6, team7, team8, team9, team10, team11, team12, team13, teamP]